### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TrekTheEarth** [SuchByte/Macro-Deck-GHUB-Batteries#1]
May seem silly but I've got no clue how to use this plugin. MacroDeck is in pc and tab. working fine and also have Ghub. When I check the variables tab, the two you say this plugin creates don't show up. Adding the one isn't even an option because the variable types to choose from don't have 'number' in the drop down.. I've tried uninstalling and reinstalling the plugin but seems to do nothing.

**Comment by leotinoco** [comment]
This is also my case. Can someone tell me how to use it?

**Comment by leotinoco** [comment]
> is

This is also my case. Can someone tell me how to use it?

**Comment by leotinoco** [comment]
> May seem silly but I've got no clue how to use this plugin. MacroDeck is in pc and tab. working fine and also have Ghub. When I check the variables tab, the two you say this plugin creates don't show up. Adding the one isn't even an option because the variable types to choose from don't have 'number' in the drop down.. I've tried uninstalling and reinstalling the plugin but seems to do nothing.

This is also my case. Can someone tell me how to use it?

**Comment by rskolden** [comment]
> > May seem silly but I've got no clue how to use this plugin. MacroDeck is in pc and tab. working fine and also have Ghub. When I check the variables tab, the two you say this plugin creates don't show up. Adding the one isn't even an option because the variable types to choose from don't have 'number' in the drop down.. I've tried uninstalling and reinstalling the plugin but seems to do nothing.
> 
> This is also my case. Can someone tell me how to use it?

Do the following:

- Open Macro Deck
- Right click and Edit a button
- Press the small arrow in a square box next to the label box
- Select Variable at the top
- Look for something with the "_battery_level"* in it
- Select it and OK/Save

*Mine was called "proxwirelessmouse_battery_level".
